### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by MatthiasDh** [partnerhero/gapi-script#13]
Possibility to add TypeScript support? 
Typings for gapi exists if I'm not mistaken.

https://www.npmjs.com/package/@types/gapi

**Comment by iamkacperwasik** [comment]
I can try to do this

**Comment by LucasAndrad** [comment]
If you can @iamkacperwasik please go ahead.

**Comment by iamkacperwasik** [comment]
#18

**Comment by LucasAndrad** [comment]
Will check that this week @iamkacperwasik thanks!

**Comment by ddereszewski** [comment]
Any update on this PR ?

**Comment by LucasAndrad** [comment]
Sorry for the delay on this. @iamkacperwasik @ddereszewski 
Merged today, version 1.2.0 is already available.
