### ISSUE TITLE
gapi sheets

### ISSUE THREAD

**Issue by rohitshrivastava04** [partnerhero/gapi-script#16]
I am trying to access sheets using gapi, trying to follow https://developers.google.com/sheets/api/quickstart/js with gapi-script package. It says Cannot read property 'sheets' of undefined. 
Is it possible to use sheets api v4 with your package?

**Comment by LucasAndrad** [comment]
Yes you should be able to Google Sheets api v4, just make sure to add the correct scopes when you initialize auth2: [gapi sheets scopes](https://developers.google.com/identity/protocols/oauth2/scopes#sheets).
