### ISSUE TITLE
Suddenly getting 404 from loading gapi

### ISSUE THREAD

**Issue by roncodes** [partnerhero/gapi-script#7]
Receiving 404 error when using this package to load gapi

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.pt_BR.vsOTtm1e9zc.O/m=auth2,signin2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCNFFxLytxdeIP4uMS7aHRAqJJ7puQ/cb=gapi.loaded_0 net::ERR_ABORTED 404

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.pt_BR.vsOTtm1e9zc.O/m=signin2/exm=auth2,signin2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCNFFxLytxdeIP4uMS7aHRAqJJ7puQ/cb=gapi.loaded_1 net::ERR_ABORTED 404

**Comment by phuoc-insignia** [comment]
same issue

**Comment by jasonwu2153** [comment]
I am also having this issue.

**Comment by aco711** [comment]
Looks like this file changed (https://apis.google.com/js/platform.js) Was able to fix it locally when I updated `gapiScript.js` to use new code. A little busy today but will try to submit a PR as soon as I can.
